apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: web-api
build:
  insecureRegistries:
    - localhost:5000
  tagPolicy:
    sha256: {}

  artifacts:
    - image: "localhost:5000/dotnet-with-skaffold-web-api"
      custom:
        buildCommand: |
          dotnet publish web-api /t:PublishContainer 

manifests:
  rawYaml:
    - k8s/web-api.yaml

portForward:
  - resourceType: deployment
    namespace: dotnet-with-skaffold
    resourceName: web-api
    port: 8080
    localPort: 8085