apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: web-api
build:
  artifacts:
    - image: localhost:5001/dotnet-with-skaffold-web-api
      custom:
        buildCommand: |
          dotnet publish web-api /t:PublishContainer 

manifests:
  rawYaml:
    - k8s/web-api.yaml

portForward:
  - resourceType: Deployment
    resourceName: web-api
    port: 8080
    localPort: 8085